koodipaja/koodipaja/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from projects.views import ProjectViewSet, ProjectPageTitleViewSet, ProjectArticleViewSet

# testing stuff
from testaus.views import QuestionAnswerPairViewSet

router = DefaultRouter()
router.register(r'project', ProjectViewSet, basename='project')
router.register(r'project_title', ProjectPageTitleViewSet, basename='project_title')
router.register(r'project_article', ProjectArticleViewSet, basename='project_article')
router.register(r'question_answer', QuestionAnswerPairViewSet, basename='question_answer')

urlpatterns = [
    path('api/', include(router.urls)),

    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('kotisivu.urls')),
    path('', include('testaus.urls')),
    path('', include('projects.urls')),

    # path('api/', include('projects.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koodipaja/kotisivu/urls.py
from django.urls import path
from . import views

app_name = 'kotisivu'

urlpatterns = [
    path('', views.kotisivu, name='kotisivu'),
    path('site-notes/', views.kotisivu_notes, name='site-notes'),
]

koodipaja/projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    
    path('delete-article/<str:pk>/', views.delete_item, name='delete-article'),
    path('delete-page-title/<str:pk>/', views.delete_item, name='delete-page-title'),
    path('list-projects/', views.listProjects, name='list-projects'),
    path('list-project-pages/<str:pk>/',
         views.viewSingleProject, name='list-project-pages'),
    path('create-project/', views.createProject, name="create-project"),
    path('create-project-tag/', views.createProjectTag, name="create-project-tag"),
    path('create-project-page/<str:pk>/',
         views.createProjectPage, name="create-project-page"),
    path('list-page-titles/<str:pk>/',
         views.viewProjectPage, name='list-page-titles'),
    path('list-page-articles/<str:pk>/',
         views.viewPageTitle, name='list-page-articles'),
    path('create-project-article/<str:pk>/',
         views.createProjectArticle, name='create-article'),
    path('update-article/<str:pk>/', views.updateArticle, name='update-article'),
    path('create-project-page-tag/<str:pk>/',
         views.createProjectPageTag, name="create-project-page-tag"),
    path('create-project-page-title/<str:pk>/',
         views.createProjectPageTitle, name='create-project-page-title'),
    path('view-article-title/<str:pk>/',
         views.viewArticleTitle, name='view-article-title'),
    path('search-page-titles/', views.search_titles, name='search-page-titles'),
    path('search-article-titles/', views.search_articles,
         name='search-article-titles'),
]

app_name = 'projects'

koodipaja/testaus/urls.py
from django.urls import path
from . import views
from .views import cards_test_page, get_data, test_modelx

app_name = "testaus"

urlpatterns = [
    path('test_modelx/', test_modelx, name='test_modelx'),
    path('add_model_x/', views.add_model_x, name='add_model_x'),

    path('cards_test_page/', cards_test_page, name='cards_test_page'), # cards_test.html
    path('get_data/', get_data, name='get_data'),


    path('testing/', views.testingHomepage, name='testing'),

    path('general/', views.general_testing, name='general-testing'),

    path('test-page/', views.empty_test_page, name='empty-test-page'),

    path('toggle/<int:pk>/', views.toggle_boolean, name='toggle-boolean'),

    path('muistipeli/', views.muistipeli, name='muistipeli'),

    path('create-malli-1/', views.create_malli1, name='create-malli-1'),
    path('new-muistipeli/', views.new_muistipeli, name='new-muistipeli'),
    path('move-active/<int:pk>/',
         views.move_question_to_active, name='move-question-to-active'),
    path('move-inactive/<int:pk>/',
         views.move_question_to_inactive, name='move-question-to-inactive'),

    path('send_dict/', views.send_dictionary, name='send-dict'),
    
]

koodipaja/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('account/', views.userAccount, name="account"),
    path('favorite-articles/', views.show_favorite_articles,
         name="favorite-articles"),
]

koodipaja/templates/main.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Koodipaja</title>

  <link rel="stylesheet" href="{% static 'main.css' %}" />

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
  <!-- <script type="module" src="https://md-block.verou.me/md-block.js"></script> -->
</head>

<body class="body">
  <!-- Navigation bar -->

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <!-- Navigation bar links -->

          <!-- Home page -->
          <a style="padding-left: 5px; padding-right: 5px" class="nav-link"
            href="{% url 'kotisivu:kotisivu' %}">Home</a>

          <a class="nav-link" href="">|</a>

          <!-- My page / Account page -->
          <a style="padding-left: 5px; padding-right: 5px" class="nav-link" href="{% url 'users:account' %}">My Page</a>

          <a class="nav-link" href="">|</a>

          <!-- Projects page -->
          <a style="padding-left: 5px; padding-right: 5px" class="nav-link"
            href="{% url 'projects:list-projects' %}">Projects</a>

          <a class="nav-link" href="">|</a>

          <!-- Empty Testing page -->
          <a style="padding-left: 5px; padding-right: 5px" class="nav-link"
            href="{% url 'testaus:empty-test-page' %}">Testing</a>

          <a class="nav-link" href="">|</a>

          <!-- Admin page -->
          <a style="padding-left: 5px; padding-right: 5px" class="nav-link" href="/admin/">Admin</a>

          <a class="nav-link" href="">|</a>
        </div>

        <!-- Search dropdown -->

        <div class="dropdown">
          <button class="dropbtn">Search</button>
          <i class="fa fa-caret-down"></i>
          <div class="dropdown-content">
            <!-- Search by page title -->
            <div style="overflow: hidden; white-space: nowrap">
              <a href="{% url 'projects:search-page-titles' %}">Page Titles</a>
            </div>

            <!-- Search by article title -->
            <div style="overflow: hidden; white-space: nowrap">
              <a href="{% url 'projects:search-article-titles' %}">Article Titles</a>
            </div>
          </div>
        </div>
      </div>
      <div>
        <!-- Check if user is logged in -->
        {% if request.user.is_authenticated %}
        <a href="{% url 'users:logout' %}" style="padding-left: 5px; padding-right: 5px" class="nav-link">Logout</a>

        <!-- If user is not logged in -->
        {% else %}
        <a href="{% url 'users:login' %}" style="padding-left: 5px; padding-right: 5px" ; class="nav-link">Login/Sign
          up</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <!-- Site notes link conditional rendering -->
  {% if page == 'kotisivu' %}

  <a style="font-size: larger; padding-top: 5px" href="{% url 'kotisivu:site-notes' %}">View site notes</a>

  {% else %} {% endif %} {% block content %} {% endblock content %}

  <br />
  <!-- <p>FOOTER</p> -->
</body>

<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/favorite_button.js' %}"></script>
<script src="{% static 'js/toggleContentVisibility.js' %}"></script>
<script src="{% static 'js/showHideClass.js' %}"></script>

</html>

koodipaja/templates/main_testing.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #333;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>
</head>
<body>

<div class="navbar">
  <a href="{% url 'kotisivu:kotisivu' %}">Home</a>
  <a href="#news">News</a>
  <div class="dropdown">
    <button class="dropbtn">Dropdown 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Link 1</a>
      <a href="#">Link 2</a>
      <a href="#">Link 3</a>
    </div>
  </div> 
</div>

<h3>Dropdown Menu inside a Navigation Bar</h3>
<p>Hover over the "Dropdown" link to see the dropdown menu.</p>

<div class="dropdown">
  <p>Mouse over me</p>
  <div class="dropdown-content">
  <a href="#">Hello World!</a>
  <a href="#">Hello World!</a>
  <a href="#">Hello World!</a>
  <a href="#">Hello World!</a>
  <a href="#">Hello World!</a>
  </div>
</div>

</body>
</html>

koodipaja/templates/pagination.html
{% if queryset.has_other_pages %} <!--  wrap the whole pagination div.
    if there's only 1 page, don't output pagination -->
<div class="pagination">

    {% if queryset.has_previous %} <!-- has_previous() method-->
    <li style=><a style="background-color:rgb(130, 213, 255)" href="?page={{queryset.previous_page_number}}"
            class="btn page-link" data-page="{{queryset.previous_page_number}}">&#10094;&nbsp;Prev</a></li>
    <!-- left arrow symbol: &#10094 -->
    {% endif %}


    {% for page in custom_range %}

    {% if page == queryset.number %} <!-- style the current page button -->
    <li><a style="background-color:rgb(130, 213, 255)" href="?page={{page}}" class="btn page-link btn--sub"
            data-page="{{page}}">{{page}}</a></li>
    {% else %}
    <li><a style="background-color:rgb(130, 213, 255)" href="?page={{page}}" class="btn page-link"
            data-page="{{page}}">{{page}}</a>
    </li>
    <!-- theme might affect appearance of buttons -->
    {% endif %}
    {% endfor %}

    {% if queryset.has_next %} <!-- has_previous() method-->
    <li><a style="background-color:rgb(130, 213, 255)" href="?page={{queryset.next_page_number}}" class="btn page-link"
            data-page="{{queryset.next_page_number}}">Next &#10095;&nbsp;</a></li>
    <!-- right arrow symbol: &#10095 -->
    {% endif %}
</div>
{% endif %}

koodipaja/templates/reset.html
{% extends "main.html" %}

{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Enter new password</h3>

            <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/templates/reset_password.html
{% extends "main.html" %}

{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset</h3>

            <p>Forgotten your password? Enter tyour email address below, and we'll email instructions for settings a new
                one.</p>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/templates/reset_password_complete.html
{% extends "main.html" %}

{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset complete</h3>

            <p>Your password has been set. You may go ahead and log in now.</p>

            <br>

            <a href="{% url 'users:login' %}">Login</a>

        </div>
    </div>
</main>

{% endblock content %}

koodipaja/templates/reset_password_sent.html
{% extends "main.html" %}

{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset sent</h3>

            <p>We've emailed you instructions for setting your password, if an account exists with the email you
                entered. You should receive them shortly.</p>
            
            <br>

            <p>If you don't receive an email, please make sure you've entered the address you registered with, and check
                your spam folder.</p>

        </div>
    </div>
</main>

{% endblock content %}

koodipaja/templates/site_notes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Jep jep</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  <script type="module" src="https://md-block.verou.me/md-block.js"></script>

</head>

<body class="body">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a style="padding-left: 5px; padding-right: 5px;" class="nav-link"
            href="{% url 'kotisivu:kotisivu' %}">Home</a>
          <a class="nav-link" href="">-</a>
          <a style="padding-left: 5px; padding-right: 5px;" class="nav-link"
            href="{% url 'projects:list-projects' %}">Projects</a>
          <a class="nav-link" href="">-</a>
        </div>
        <div class="dropdown">
          <button class="dropbtn">Search</button>
          <i class="fa fa-caret-down"></i>
          <div class="dropdown-content">
          </div>
        </div>
      </div>
    </div>
  </nav>

  <br>
  <h2>Welcome to site_notes.html!</h2>
  <hr>
  <h3 style="padding-bottom: 10px;">Here's some info about what's been going on in the site's development:
  </h3>
  <p style="font-size: 20px;"> Added a 'Go Back' link to ease navigation.</p>
  <p style="font-size: 20px;"> User can create projects, project pages and articles to those pages now.</p>
  <p style="font-size: 20px;"> Can now create projects etc with the help of forms.</p>
  <p style="font-size: 20px;"> Added some initial values to most forms.</p>
  <p style="font-size: 20px;"> Searching capability in development.</p>
  <hr>
  <h3 style="padding-bottom: 10px;">Development goals and ideas:</h3>
  <strong style="font-size: 20px;">Working on currently: </strong><span style="font-size: 20px;">&nbsp;Implement
    searching.</span><br><br>
  <p style="font-size: 20px;"> Delete and update forms, still need to do that in the admin panel.</p>
  <p style="font-size: 20px;"> Projects app: ProjectArticleTag form, update and delete forms.</p>
  <p style="font-size: 20px;"> Ability to add/edit/remove comments or such to a page might be useful. Need to think
    about
    it.</p>
  <p style="font-size: 20px;"> Create a login page. Most pages require the user to be logged in. (creating a superuser
    and profile works)</p>
  <p style="font-size: 20px;"> Try making a signal that automatically creates a profile when creating a new user.</p>
  <p style="font-size: 20px;"> Improvement of this page, at the moment it's hardcoded. Is not a priority but might be
    nice.</p>
  {% block content %}
  {% endblock content %}

  <br>
  <!-- <p style="font-size: 20px;">FOOTER</p> -->
</body>
<script src="{% static 'js/main.js' %}"></script>

</html>