koodipaja/koodipaja/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from projects.views import ProjectViewSet, ProjectPageTitleViewSet, ProjectArticleViewSet

# testing stuff
from testaus.views import QuestionAnswerPairViewSet

router = DefaultRouter()
router.register(r'project', ProjectViewSet, basename='project')
router.register(r'project_title', ProjectPageTitleViewSet, basename='project_title')
router.register(r'project_article', ProjectArticleViewSet, basename='project_article')
router.register(r'question_answer', QuestionAnswerPairViewSet, basename='question_answer')

urlpatterns = [
    path('api/', include(router.urls)),

    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('kotisivu.urls')),
    path('', include('testaus.urls')),
    path('', include('projects.urls')),

    # path('api/', include('projects.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koodipaja/projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    
    path('delete-article/<str:pk>/', views.delete_item, name='delete-article'),
    path('delete-page-title/<str:pk>/', views.delete_item, name='delete-page-title'),
    path('list-projects/', views.listProjects, name='list-projects'),
    path('list-project-pages/<str:pk>/',
         views.viewSingleProject, name='list-project-pages'),
    path('create-project/', views.createProject, name="create-project"),
    path('create-project-tag/', views.createProjectTag, name="create-project-tag"),
    path('create-project-page/<str:pk>/',
         views.createProjectPage, name="create-project-page"),
    path('list-page-titles/<str:pk>/',
         views.viewProjectPage, name='list-page-titles'),
    path('list-page-articles/<str:pk>/',
         views.viewPageTitle, name='list-page-articles'),
    path('create-project-article/<str:pk>/',
         views.createProjectArticle, name='create-article'),
    path('update-article/<str:pk>/', views.updateArticle, name='update-article'),
    path('create-project-page-tag/<str:pk>/',
         views.createProjectPageTag, name="create-project-page-tag"),
    path('create-project-page-title/<str:pk>/',
         views.createProjectPageTitle, name='create-project-page-title'),
    path('view-article-title/<str:pk>/',
         views.viewArticleTitle, name='view-article-title'),
    path('search-page-titles/', views.search_titles, name='search-page-titles'),
    path('search-article-titles/', views.search_articles,
         name='search-article-titles'),
]

app_name = 'projects'

koodipaja/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('account/', views.userAccount, name="account"),
    path('favorite-articles/', views.show_favorite_articles,
         name="favorite-articles"),
]

koodipaja/projects/forms.py
from django import forms
from django.forms import ModelForm
# from django import forms
from .models import (Project, ProjectTag, ProjectPage, ProjectPageTag, ProjectArticle,
                     ProjectArticleTag, ProjectPageTitle)


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['owner', 'title', 'body', 'tags']


class ProjectTagForm(ModelForm):
    class Meta:
        model = ProjectTag
        fields = ['name']


class ProjectPageForm(ModelForm):
    class Meta:
        model = ProjectPage
        fields = ['owner', 'project', 'title', 'page_number', 'tags']
        widgets = {
            'owner': forms.Select(),
            'project': forms.Select(),
        }


class ProjectPageTitleForm(ModelForm):
    class Meta:
        model = ProjectPageTitle
        fields = ['owner', 'project', 'project_page', 'title']
        widgets = {
            'owner': forms.Select(),
            'project': forms.Select(),
            'project_page': forms.Select(),
        }


class ProjectPageTagForm(ModelForm):
    class Meta:
        model = ProjectPageTag
        fields = ['name']


class ProjectArticleForm(ModelForm):
    class Meta:
        model = ProjectArticle
        fields = ['owner', 'project', 'project_page',
                  'article_title', 'title', 'body', 'tags']
        widgets = {
            'owner': forms.Select(),
            'project': forms.Select(),
            'project_page': forms.Select(),
            'article_title': forms.Select(),
            'title':forms.TextInput(attrs={'size': 147}),
            'body': forms.Textarea(attrs={'rows': 50, 'cols': 150}),
        }


class UpdateProjectArticleForm(ModelForm):
    class Meta:
        model = ProjectArticle
        fields = ['title', 'body']
        widgets = {
            'body': forms.Textarea(attrs={'rows':50, 'cols': 150}),
            'title':forms.TextInput(attrs={'size': 147}),
        }


class ProjectArticleTagForm(ModelForm):
    class Meta:
        model = ProjectArticleTag
        fields = ['name']

koodipaja/projects/views.py
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from users.models import Profile
from .models import Project, ProjectPage, ProjectPageTitle, ProjectArticle
from .forms import (ProjectForm, ProjectTagForm, ProjectPageForm, ProjectArticleForm,
                    ProjectPageTagForm, ProjectPageTitleForm, UpdateProjectArticleForm)
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import resolve
from .utils import searchProjects, paginateProjects, utils_search_articles, utils_search_titles
from urllib.parse import urlparse
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from .serializers import ProjectSerializer, ProjectPageTitleSerializer, ProjectArticleSerializer
from pprint import pprint

# API


class ProjectViewSet(viewsets.ModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer

class ProjectPageTitleViewSet(viewsets.ModelViewSet):
    queryset = ProjectPageTitle.objects.all()
    serializer_class = ProjectPageTitleSerializer

class ProjectArticleViewSet(viewsets.ModelViewSet):
    queryset = ProjectArticle.objects.all()
    serializer_class = ProjectArticleSerializer
    
    @action(detail=True, methods=['get', 'put', 'patch', 'delete'])
    def update_and_delete(self, request, pk=None):
        # Your update and delete logic here
        return Response({'detail': 'Update and delete response'})
    
    # @action(detail=False, methods=['get'])
    # def custom_action(self, request, pk=None):
    #     # Your custom action logic here
    #     return Response({'detail': 'Custom action response'})

# Views

@login_required(login_url='users:login')
def search_articles(request):

    profile = request.user.profile

    # need to get the return values
    articles, search_query = utils_search_articles(request)

    custom_range, articles = paginateProjects(request, articles, 10)

    # removed 'paginator':paginator from context because using the custom range
    context = {
        'articles': articles, 'search_query': search_query, 'custom_range': custom_range,
        'profile': profile
    }

    # pprint(context)
    return render(request, 'projects/search_article_titles.html', context)


@login_required(login_url='users:login')
def search_titles(request):

    profile = request.user.profile

    # need to get the return values
    titles, search_query = utils_search_titles(request)

    custom_range, titles = paginateProjects(request, titles, 10)

    # removed 'paginator':paginator from context because using the custom range
    context = {
        'titles': titles, 'search_query': search_query, 'custom_range': custom_range,
        'profile': profile
    }

    # pprint(context)
    return render(request, 'projects/search_page_titles.html', context)

# Delete #
@login_required(login_url='users:login')
def delete_item(request, pk):
    # Get the query parameter
    from_page = request.GET.get('from')
    print(f"Query Parameter 'from': {from_page}")  # Debug

    if not from_page:
        return HttpResponseNotFound("Invalid or missing 'from' parameter.")

    if from_page == 'list-page-articles':
        # Handle deletion for articles
        page_title = get_object_or_404(ProjectPageTitle, projectarticle__id=pk)
        article_to_delete = get_object_or_404(ProjectArticle, id=pk)

        if request.method == 'POST':
            article_to_delete.delete()
            return redirect('projects:list-page-articles', pk=page_title.id)

        return render(request, 'delete.html', {'article_to_delete': article_to_delete, 'page': 'list-page-articles', 'page_title': page_title})

    elif from_page == 'list-page-titles':
        # Handle deletion for page titles
        project_page = get_object_or_404(ProjectPage, projectpagetitle__id=pk)
        page_title_to_delete = get_object_or_404(ProjectPageTitle, id=pk)

        if request.method == 'POST':
            page_title_to_delete.delete()
            return redirect('projects:list-page-titles', pk=project_page.id)

        return render(request, 'delete.html', {'page_title_to_delete': page_title_to_delete, 'page': 'list-page-titles', 'project_page': project_page})

    # Fallback for unsupported or invalid values
    return HttpResponseNotFound("Invalid delete action context.")

    
@login_required(login_url='users:login')
def listProjects(request):
    if request.user.is_authenticated:
        profile = request.user.profile
        project = profile.project_set.all()
    else:
        return redirect('users:login')

    context = {'project': project}
    return render(request, 'projects/list-projects.html', context)


@login_required(login_url='users:login')
def viewSingleProject(request, pk):
    profile = request.user.profile
    project_pages = profile.projectpage_set.filter(project__id=pk)

    context = {'project_pages': project_pages}

    context['object'] = Project.objects.get(id=pk)
    # context['object2'] = Project.objects.get(id=pk)

    return render(request, 'projects/list-project-pages.html', context)


@login_required(login_url='users:login')
def viewProjectPage(request, pk):
    profile = request.user.profile
    page_titles = profile.projectpagetitle_set.filter(project_page__id=pk)

    context = {'page_titles': page_titles}
    context['object'] = ProjectPage.objects.get(id=pk)
    context['object2'] = Project.objects.get(projectpage__id=pk)

    return render(request, 'projects/list-page-titles.html', context)


@login_required(login_url='users:login')
def viewPageTitle(request, pk):
    profile = request.user.profile
    articles = profile.projectarticle_set.filter(article_title__id=pk)

    context = {'articles': articles}
    context['object'] = ProjectPageTitle.objects.get(id=pk)
    context['object2'] = ProjectPage.objects.get(projectpagetitle__id=pk)

    return render(request, 'projects/list-articles.html', context)


@login_required(login_url='users:login')
def viewArticleTitle(request, pk):
    profile = request.user.profile
    article_title = profile.projectarticle_set.get(id=pk)
    # pprint(ProjectArticle._meta.get_fields())
    

    # testing utils generate_url
    # print(generate_url('projects:view-article-title',pk))
    
    # article_object = get_object_or_404(ProjectArticle, pk=pk)
    if request.method == "POST":
        # Toggle the BooleanField value
        article_title.favorite = not article_title.favorite
        article_title.save()

        return redirect('projects:view-article-title', pk)

    context = {'article_title': article_title}
    context['object2'] = ProjectPageTitle.objects.get(projectarticle__id=pk)

    return render(request, 'projects/view-article-title.html', context)


# FORMS

@login_required(login_url='users:login')
def updateArticle(request, pk):
    instance = get_object_or_404(ProjectArticle, pk=pk)    
    page_title = ProjectPageTitle.objects.get(projectarticle__id=pk)
    if request.method == 'POST':
        form = UpdateProjectArticleForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('projects:list-page-articles', page_title.id)
    else:
        # context['object'] = ProjectArticle.objects.get(projectarticle__id=pk)     
        form = UpdateProjectArticleForm(instance=instance)
        context = {'form': form}
    return render(request, 'projects/updateprojectarticle_form.html', context)

@login_required(login_url='users:login')
def createProject(request):
    form = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('projects:list-projects')

    context = {'form': form}
    return render(request, "projects/project_form.html", context)


@login_required(login_url='users:login')
def createProjectTag(request):
    form = ProjectTagForm()

    if request.method == 'POST':
        form = ProjectTagForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('projects:list-projects')

    context = {'form': form}
    return render(request, "projects/projecttag_form.html", context)


@login_required(login_url='users:login')
def createProjectPage(request, pk):
    profile = request.user.profile
    project = Project.objects.get(id=pk)
    # count_pages = len(ProjectPage.objects.filter(project__title__startswith='EKA'))
    count_pages = len(ProjectPage.objects.filter(project_id=pk))
    page_number = count_pages + 1
    page_title = str('Page '+f'{page_number}')
    form = ProjectPageForm(initial={'owner': profile, 'project': project,
                                    'page_number': page_number, 'title': f'{page_title}'})

    if request.method == 'POST':
        form = ProjectPageForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('projects:list-project-pages', pk)

    context = {'form': form}
    context['object'] = Project.objects.get(id=pk)
    return render(request, "projects/projectpage_form.html", context)


@login_required(login_url='users:login')
def createProjectPageTitle(request, pk):
    profile = request.user.profile
    project = Project.objects.get(projectpage__id=pk)
    project_page = ProjectPage.objects.get(id=pk)
    form = ProjectPageTitleForm(initial={'owner': profile, 'project': project,
                                         'project_page': project_page})

    if request.method == 'POST':
        form = ProjectPageTitleForm(request.POST)

koodipaja/projects/templates/projects/haku2.html
{% extends 'main.html' %}
{% block content %}


<!-- Main Section -->
<main>
    <section>
        <div>
            <div>
                <h2>Search for <span>Stuff</span></h2>
            </div>

            <div>
                <form id="searchForm" class="form" action="" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search By Articles </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Search by Project Title" value="{{search_query}}" />
                    </div>

                    <!-- <input class="btn btn--sub btn--lg" type="submit" value="Search" /> -->
                </form>
                <br>
            </div>
        </div>
    </section>
    <!-- Search Results: -->
    {% for article in articles %}
    <a href="{% url 'projects:view-article-title' article.id %}">
        <p>{{article.title}}</p>
    </a>
    {% endfor %}

    <br>

    {% include "pagination.html" with queryset=articles custom_range=custom_range %}

</main>


{% endblock content %}

koodipaja/projects/templates/projects/list-articles.html
{% extends "main.html" %} {% block content %}

<div class="project-top-div">
  <a class="project-top-link" style="font-size: x-large" href="{% url 'projects:list-page-titles' object2.id %}">Go
    Back -&nbsp;</a>
  <a class="project-top-link" style="font-size: x-large"
    href="{% url 'projects:create-article' object.id %}?next={{request.path}}">Create new
    article -&nbsp;</a>
  <span class="project-top-link" href="#" id="VisibilityButton" style="font-size: x-large;cursor: pointer;"
    onclick="renameElements()">
    Update Article</span>
</div>
<hr class="project-top-hr" />
{% for article in articles %}
<table>
  <tr>
    <th></th>
    <td>
      <a style="font-size: x-large" href="{% url 'projects:view-article-title' article.id %}">
        {{article.title}}&nbsp;&nbsp;
      </a>
    </td>
    <td>
      <div class="hide">
        <a style="font-size: x-large;text-decoration: underline;"
          href="{% url 'projects:update-article' article.id %}?next={{request.path}}">Update</a>
        <a style="font-size: x-large;text-decoration: underline;"
          href="{% url 'projects:delete-article' article.id %}?from=list-page-articles">&nbsp;&nbsp;Delete</a>
      </div>
    </td>
  </tr>
</table>

{% endfor %} {% endblock content %}

koodipaja/projects/templates/projects/list-page-titles.html
{% extends "main.html" %} {% block content %}

<div class="project-top-div">
  <a class="project-top-link" style="font-size: x-large" href="{% url 'projects:list-project-pages' object2.id %}">Go
    Back -&nbsp;</a>
  <a class="project-top-link" style="font-size: x-large"
    href="{% url 'projects:create-project-page-title' object.id %}?next={{request.path}}">Create new title -&nbsp;</a>
  <span class="project-top-link" href="#" id="VisibilityButton" style="font-size: x-large;cursor: pointer;"
    onclick="renameElements()">
    Update Options</span>
</div>
<hr class="project-top-hr" />
{% for title in page_titles %}
<table>
  <tr>
    <th></th>
    <td>
      <a style="font-size: x-large" href="{% url 'projects:list-page-articles' title.id %}">
        {{title.title}}
      </a>
    </td>
    <td>
      <div class="hide">
        <a style="font-size: x-large;text-decoration: underline;"
          href="{% url 'projects:delete-page-title' title.id %}?from=list-page-titles">&nbsp;&nbsp;Delete</a>
      </div>
    </td>
  </tr>
</table>

{% endfor %} {% endblock content %}

koodipaja/projects/templates/projects/list-project-pages.html
{% extends "main.html" %}

{% block content %}

<div class="project-top-div">
    <a class="project-top-link" style="font-size: x-large" href="{% url 'projects:list-projects' %}">Go Back -&nbsp;</a>
    <a class="project-top-link" style="font-size: x-large" href="{% url 'projects:create-project-page' object.id %}">Add
        new
        page -&nbsp;</a><a class="project-top-link" style="font-size: x-large"
        href="{% url 'projects:create-project-page-tag' object.id %}">New Page Tag</a>
</div>
<hr class="project-top-hr">

{% for page in project_pages %}
<table>
    <tr>
        <th></th>
        <td>
            <a style="font-size:x-large;"
                href="{% url 'projects:list-page-titles' page.id %}?next={{request.path}}">{{page.title}}</a>
        </td>
    </tr>
</table>
{% endfor %}

<br>

{% endblock content %}

koodipaja/projects/templates/projects/list-projects.html
{% extends "main.html" %}

{% block content %}

<div class="project-top-div">
    <a class="project-top-link" style="font-size: x-large"
        href="{% url 'projects:create-project' %}?next={{request.path}}">New Project -&nbsp;</a><a
        class="project-top-link" style="font-size: x-large"
        href="{% url 'projects:create-project-tag' %}?next={{request.path}}">New Project
        Tag</a>
</div>
<hr class="project-top-hr" style="margin-bottom: 5px;">

{% for xx in project %}
<table>
    <tr>
        <th></th>
        <td>
            <a style="font-size:x-large;" href="{% url 'projects:list-project-pages' xx.id %}">
                <h3>{{xx.title}}</h3>
            </a>
        </td>
    </tr>
    <tr>
        <th></th>
        <td></td>
    </tr>
</table>
{% endfor %}

{% endblock content %}

<!-- <a href="{% url 'projects:view-project' xx.id %}">{{xx.title}}</a> -->

koodipaja/projects/templates/projects/project_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <a href="{{ request.GET.next }}">Go Back</a>
            <hr>

            <form class="form" action=""  method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                            <td>
                                <label>{{field.label}}</label>
                            </td>
                        </th>
                    </tr>
                    <tr><th><td>
                        {{field}}
                    </td></th></tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/projectarticle_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <div class="project-top-div">
                <a class="project-top-link" style="font-size: x-large"
                    href="{% url 'projects:list-page-articles' page_id.id %}">Go
                    Back</a>
            </div>
            <hr class="project-top-hr" />

            <form class="form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                        <td>
                            <label>
                                {{field.label}}
                            </label>
                        </td>
                        </th>
                    </tr>
                    <tr>
                        <th>
                        <td>
                            {{field}}
                        </td>
                        </th>
                    </tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/projectpage_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div >
        <div >
            <a class="backButton" href="{% url 'projects:view-single-project' object.id %}">Go Back</a>
            <hr>

            <form class="form" action=""  method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                            <td>
                                <label for="formInput#text">{{field.label}}</label>
                            </td>
                        </th>
                    </tr>
                    <tr><th><td>
                        {{field}}
                    </td></th></tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/projectpagetag_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <a class="backButton" href="{% url 'projects:list-project-pages' object.id %}">Go Back</a>
            <hr>

            <form class="form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                        <td>
                            <label>{{field.label}}</label>
                        </td>
                        </th>
                    </tr>
                    <tr>
                        <th>
                        <td>
                            {{field}}
                        </td>
                        </th>
                    </tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/projectpagetitle_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <div class="project-top-div">
                <a class="project-top-link" style="font-size: x-large"
                    href="{% url 'projects:list-page-titles' object.id %}">Go
                    Back</a>
            </div>
            <hr class="project-top-hr" />

            <form class="form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                        <td>
                            <label for="formInput#text">{{field.label}}</label>
                        </td>
                        </th>
                    </tr>
                    <tr>
                        <th>
                        <td>
                            {{field}}
                        </td>
                        </th>
                    </tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/projecttag_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <a href="{{ request.GET.next }}">Go Back</a>
            <hr>

            <form class="form" action=""  method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                            <td>
                                <label>{{field.label}}</label>
                            </td>
                        </th>
                    </tr>
                    <tr><th><td>
                        {{field}}
                    </td></th></tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/search_article_titles.html
{% extends 'main.html' %} {% block content %}

<!-- Main Section -->
<main>
  <section>
    <div>
      <div>
        <p style="font-size: 30px; padding-top: 10px">
          Search for article titles:
        </p>
      </div>
      <div>
        <form id="searchForm" class="form" action="" method="get">
          <div class="form__field">
            <input
              style="width: 300px"
              class="input input--text"
              id="formInput#search"
              type="text"
              name="search_query"
              placeholder="Search..."
              value="{{search_query}}"
            />
          </div>
          <hr />
        </form>
      </div>
    </div>
  </section>

  <!-- Search Results: -->
  {% for article in articles %} {% if article.owner == profile %}
  <a href="{% url 'projects:view-article-title' article.id %}">
    <p style="font-size: 30px">{{article.title}}</p>
  </a>
   {% else %}
   {% endif %} 
   {% endfor %}
  <br />
  {% include "pagination.html" with queryset=articles custom_range=custom_range %}
</main>

{% endblock content %}

koodipaja/projects/templates/projects/updateprojectarticle_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <a href="{{request.GET.next}}">Go Back</a>
            <hr>

            <form class="form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                        <td>
                            <label>{{field.label}}</label>
                        </td>
                        </th>
                    </tr>
                    <tr>
                        <th>
                        <td>
                            {{field}}
                        </td>
                        </th>
                    </tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

koodipaja/projects/templates/projects/view-article-title.html
{% extends "main.html" %} {% block content %}

<form method="POST">
  {% csrf_token %} {% if article_title.favorite %}
  <button>Remove from favourites</button>
  {% else %}
  <button>Add to favourites</button>
  {% endif %}
</form>
<hr />

<h4>{{article_title.title}}</h4>

<br />
<pre style="font-size: x-large">{{article_title.body}}</pre>

{% endblock content %}