koodipaja/koodipaja/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from projects.views import ProjectViewSet, ProjectPageTitleViewSet, ProjectArticleViewSet

# testing stuff
from testaus.views import QuestionAnswerPairViewSet

router = DefaultRouter()
router.register(r'project', ProjectViewSet, basename='project')
router.register(r'project_title', ProjectPageTitleViewSet, basename='project_title')
router.register(r'project_article', ProjectArticleViewSet, basename='project_article')
router.register(r'question_answer', QuestionAnswerPairViewSet, basename='question_answer')

urlpatterns = [
    path('api/', include(router.urls)),

    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('kotisivu.urls')),
    path('', include('testaus.urls')),
    path('', include('projects.urls')),

    # path('api/', include('projects.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koodipaja/projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    
    path('delete-article/<str:pk>/', views.delete_item, name='delete-article'),
    path('delete-page-title/<str:pk>/', views.delete_item, name='delete-page-title'),
    path('list-projects/', views.listProjects, name='list-projects'),
    path('list-project-pages/<str:pk>/',
         views.viewSingleProject, name='list-project-pages'),
    path('create-project/', views.createProject, name="create-project"),
    path('create-project-tag/', views.createProjectTag, name="create-project-tag"),
    path('create-project-page/<str:pk>/',
         views.createProjectPage, name="create-project-page"),
    path('list-page-titles/<str:pk>/',
         views.viewProjectPage, name='list-page-titles'),
    path('list-page-articles/<str:pk>/',
         views.viewPageTitle, name='list-page-articles'),
    path('create-project-article/<str:pk>/',
         views.createProjectArticle, name='create-article'),
    path('update-article/<str:pk>/', views.updateArticle, name='update-article'),
    path('create-project-page-tag/<str:pk>/',
         views.createProjectPageTag, name="create-project-page-tag"),
    path('create-project-page-title/<str:pk>/',
         views.createProjectPageTitle, name='create-project-page-title'),
    path('view-article-title/<str:pk>/',
         views.viewArticleTitle, name='view-article-title'),
    path('search-page-titles/', views.search_titles, name='search-page-titles'),
    path('search-article-titles/', views.search_articles,
         name='search-article-titles'),
]

app_name = 'projects'

koodipaja/testaus/urls.py
from django.urls import path
from . import views
from .views import cards_test_page, get_data, test_modelx

app_name = "testaus"

urlpatterns = [
    path('test_modelx/', test_modelx, name='test_modelx'),
    path('add_model_x/', views.add_model_x, name='add_model_x'),

    path('cards_test_page/', cards_test_page, name='cards_test_page'), # cards_test.html
    path('get_data/', get_data, name='get_data'),


    path('testing/', views.testingHomepage, name='testing'),

    path('general/', views.general_testing, name='general-testing'),

    path('test-page/', views.empty_test_page, name='empty-test-page'),

    path('toggle/<int:pk>/', views.toggle_boolean, name='toggle-boolean'),

    path('muistipeli/', views.muistipeli, name='muistipeli'),

    path('create-malli-1/', views.create_malli1, name='create-malli-1'),
    path('new-muistipeli/', views.new_muistipeli, name='new-muistipeli'),
    path('move-active/<int:pk>/',
         views.move_question_to_active, name='move-question-to-active'),
    path('move-inactive/<int:pk>/',
         views.move_question_to_inactive, name='move-question-to-inactive'),

    path('send_dict/', views.send_dictionary, name='send-dict'),
    
]

koodipaja/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('account/', views.userAccount, name="account"),
    path('favorite-articles/', views.show_favorite_articles,
         name="favorite-articles"),
]

koodipaja/users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)

koodipaja/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']

        # customize the field labels
        labels = {
            'first_name': 'Name'
        }

    # def __init__(self, *args, **kwargs):
    #     super(CustomUserCreationForm, self).__init__(*args, **kwargs)

    #     # the field(s) we want to modify
    #     # self.fields['title'].widget.attrs.update({'class':'input', # CSS class, not Python class.
    #     #                                         'placeholder':'Add title'})
    #     # self.fields['description'].widget.attrs.update({'class':'input'}) # _form.css line 43 is the class in question

    #     # do it with a for loop
    #     for name, field in self.fields.items():
    #         field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username', 'location',
                  'bio', 'short_intro', 'social_github', 'social_linkedin',
                  'social_twitter', 'social_youtube', 'social_website']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


# class SkillForm(ModelForm):
#     class Meta:
#         model = Skill
#         fields ='__all__'
#         exclude = ['owner']

#     def __init__(self, *args, **kwargs):
#         super(SkillForm, self).__init__(*args, **kwargs)

#         for name, field in self.fields.items():
#             field.widget.attrs.update({'class': 'input'})


# class MessageForm(ModelForm):
#     class Meta:
#         model = Message
#         fields = ['name', 'email', 'subject', 'body']


#     def __init__(self, *args, **kwargs):
#         super(MessageForm, self).__init__(*args, **kwargs)

#         for name, field in self.fields.items():
#             field.widget.attrs.update({'class': 'input'})

koodipaja/users/views.py
from pprint import pprint
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from django.urls import conf
from .forms import CustomUserCreationForm
from .models import Profile
from projects.models import ProjectArticle
from testaus.models import Muistipeli


def loginUser(request):

    # first check if the user is already authenticated
    if request.user.is_authenticated:
        return redirect('projects:list-projects')

    if request.method == 'POST':
        # print(request.POST)
        # extract by form fields
        username = request.POST['username'].lower()
        password = request.POST['password']

        # check that the username exists in the database
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        # authenticate checks that the password matches the username and return either the
        # user instance or None
        user = authenticate(request, username=username, password=password)

        # run a check in case the authentication succeeds or fails
        if user is not None:
            # login function will create a session for the user in the database in the sessions table
            # and add that into our browser's cookies.
            login(request, user)
            # Review_login
            return redirect(request.GET['next'] if 'next' in request.GET else 'projects:list-projects')
        else:
            messages.error(request, 'Username or password is incorrect')

    return render(request, 'users/login_register.html')


def logoutUser(request):
    # delete the session
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('users:login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # form.save()

            # hold a temporary instance of the form and create a user object which we can modify.
            # we might not want usernames to be case sensitive, for example.
            user = form.save(commit=False)
            user.username = user.username.lower()  # could be done directly in the form also
            user.save()

            messages.success(request, 'User account was created!')

            # we have the user object already thanks to commit=False earlier
            # so we just need to login and redirect
            login(request, user)
            return redirect('projects:list-projects')

        # form was not valid
        else:
            messages.error(
                request, 'An error has occured during registration!')

    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    context = {'profile': profile}
    print(context)
    return render(request, 'users/user-profile.html', context)


@login_required(login_url='users:login')
def userAccount(request):

    my_model_instance = Muistipeli.objects.all()

    return render(request, 'users/account.html', {'my_model_instance': my_model_instance})


def show_favorite_articles(request):
    articles = ProjectArticle.objects.filter(favorite=True)
    context = {'articles': articles}

    return render(request, 'users/my_favorite_articles.html', context)

koodipaja/users/templates/users/account.html
{% extends "main.html" %}
{% load static %}


{% block content %}

<div class="container">
    <div class="grid grid--three">
        <div class="column">
            <div>
                <div class="card__body">
                    <a href="{% url 'testaus:muistipeli' %}">
                        <h5>Go to Memory Cards</h5>
                    </a>
                </div>
                <a href="{% url 'testaus:muistipeli' %}"><img src="{% static 'media/users/mem-cards.jpg' %}"
                        class="card-img-top" alt="" style="width: 75%; height: 12em; object-fit: cover;"></a>
                </a>
            </div>
        </div>
        <div class="column">
            <div>
                <div class="card__body">
                    <a href="{% url 'users:favorite-articles' %}">
                        <h5>Favorite articles</h5>
                    </a>
                </div>
                <a href="{% url 'users:favorite-articles' %}"><img src="{% static 'media/users/default.jpg' %}"
                        class="card-img-top" alt="" style="width: 75%; height: 12em; object-fit:fill;"></a>
                </a>
            </div>
        </div>
    </div>
</div>
<hr>

{% endblock content %}

koodipaja/users/templates/users/login_register.html
{% extends "main.html" %}
{% load static %}
{% block content %}


{% if page == 'register' %}

<div class="auth-container">
    <div class="auth-box" style="padding-top: 10px;">
        <form action="{% url 'users:register' %}" method="POST" class="form auth-form">
            {% csrf_token %}

            {% for field in form %}
            <div class="auth-field">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                <br>
                {{ field }}

                {% for error in field.errors %}
                <p class="auth-error">{{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}

            <br>
            <div class="auth-actions">
                <input class="btn btn-primary btn-large" type="submit" value="Create Account" />
            </div>
            <br>
            <br>
        </form>

        <div class="auth-alternative">
            <p>Already have an Account?</p>
            <br>
            <a href="{% url 'users:login' %}" class="btn-secondary btn-large">Log In</a>
        </div>
    </div>
</div>




{% else %}


<div class="auth-container">
    <div class="auth-box">
        <h3 class="auth-title">Account Login</h3>
        <p class="auth-subtitle" style="font-size: 25px;">Hello, Welcome Back!</p>
        <form action="" method="POST" class="auth-form">
            {% csrf_token %}
            <div class="auth-field">
                <label for="username">Username</label>
                <input class="auth-input" id="username" type="text" name="username"
                    placeholder="Enter your username..." />
            </div>
            <div class="auth-field">
                <label for="password">Password</label>
                <input class="auth-input" id="password" type="password" name="password" placeholder="••••••••" />
            </div>
            <div class="auth-actions">
                <button class="btn btn-primary btn-large">Log In</button>
            </div>
            <br>
            <a href="{% url 'reset_password' %}" class="auth-link">Forgot Password?</a>
            <br>
        </form>
        <div class="auth-footer">
            <p>Don't have an account? <a href="{% url 'users:register' %}" class="auth-footer-link">Sign Up</a></p>
        </div>
    </div>
</div>




{% endif %}

<script src="{% static 'js/login_helper.js' %}"></script>

{% endblock content %}

koodipaja/users/templates/users/my_favorite_articles.html
{% extends "main.html" %}

{% block content %}

<!-- Main Section -->
<main class>
    <button onclick="history.back()">Go Back</button>
    <div class="layout">
        <div>
            <h3>Favorite articles</h3>
            <hr>
        </div>
        <table>
            {% for article in articles %}
            <tr>
                <td>
                    <div>
                        <h4 class="article-title" href="{% url 'projects:view-article-title' article.id %}">
                            {{article.title}}</h4>

                        <pre style="display:none" class="favourite-article-content"
                            id="fav-article">{{article.body}}</pre>
                    </div>
                    <hr>
                </td>
            </tr>
            {% endfor %}

        </table>
    </div>
    </div>
</main>

{% endblock content %}

koodipaja/users/templates/users/user-profile.html
{% extends "main.html" %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.short_intro}}</p>
                        <p class="dev__location">{{profile.location}}</p>
                        <ul class="dev__social">
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">{{profile.bio}}</p>
                </div>
            </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}