koodipaja/koodipaja/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from projects.views import ProjectViewSet, ProjectPageTitleViewSet, ProjectArticleViewSet

# testing stuff
from testaus.views import QuestionAnswerPairViewSet

router = DefaultRouter()
router.register(r'project', ProjectViewSet, basename='project')
router.register(r'project_title', ProjectPageTitleViewSet, basename='project_title')
router.register(r'project_article', ProjectArticleViewSet, basename='project_article')
router.register(r'question_answer', QuestionAnswerPairViewSet, basename='question_answer')

urlpatterns = [
    path('api/', include(router.urls)),

    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('kotisivu.urls')),
    path('', include('testaus.urls')),
    path('', include('projects.urls')),

    # path('api/', include('projects.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koodipaja/testaus/urls.py
from django.urls import path
from . import views
from .views import cards_test_page, get_data, test_modelx

app_name = "testaus"

urlpatterns = [
    path('test_modelx/', test_modelx, name='test_modelx'),
    path('add_model_x/', views.add_model_x, name='add_model_x'),

    path('cards_test_page/', cards_test_page, name='cards_test_page'), # cards_test.html
    path('get_data/', get_data, name='get_data'),


    path('testing/', views.testingHomepage, name='testing'),

    path('general/', views.general_testing, name='general-testing'),

    path('test-page/', views.empty_test_page, name='empty-test-page'),

    path('toggle/<int:pk>/', views.toggle_boolean, name='toggle-boolean'),

    path('muistipeli/', views.muistipeli, name='muistipeli'),

    path('create-malli-1/', views.create_malli1, name='create-malli-1'),
    path('new-muistipeli/', views.new_muistipeli, name='new-muistipeli'),
    path('move-active/<int:pk>/',
         views.move_question_to_active, name='move-question-to-active'),
    path('move-inactive/<int:pk>/',
         views.move_question_to_inactive, name='move-question-to-inactive'),

    path('send_dict/', views.send_dictionary, name='send-dict'),
    
]

koodipaja/testing/urls.py
from django.urls import path
from . import views

app_name = "testing"

urlpatterns = [
    path('testing/', views.testingHomepage, name='testing'),
    path('viewtest1/<str:pk>/', views.viewTest1, name='viewtest1'),
    path('viewtest2/<str:pk>/', views.viewTest2, name='viewtest2'),


    path('test_languages/', views.test_listLanguages, name='test_languages'),
]

koodipaja/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('account/', views.userAccount, name="account"),
    path('favorite-articles/', views.show_favorite_articles,
         name="favorite-articles"),
]

koodipaja/testaus/models.py
from django.db import models
from users.models import Profile
from django.urls import reverse


class Person(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=128)
    members = models.ManyToManyField(Person, through='Membership')

    def __str__(self):
        return self.name


class Membership(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateField()
    invite_reason = models.CharField(max_length=64)


class MyModel(models.Model):
    my_boolean_field = models.BooleanField(default=False)
    id = models.AutoField(primary_key=True)


# Memory game

class Muistipeli(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.SET_NULL)
    featured_image = models.ImageField(
        null=True, blank=True, upload_to="users/", default="default.jpg")
    title = models.CharField(max_length=200)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
        return url


class Malli1(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.SET_NULL)
    muistipeli = models.ForeignKey(
        Muistipeli, on_delete=models.CASCADE, null=True)
    question = models.CharField(max_length=500, null=True, blank=True)
    answer = models.CharField(max_length=2000, null=True, blank=True)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.question


class Malli2(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.SET_NULL)
    muistipeli = models.ForeignKey(
        Muistipeli, on_delete=models.CASCADE, null=True)
    question = models.CharField(max_length=500, null=True, blank=True)
    answer = models.CharField(max_length=2000, null=True, blank=True)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.question


class QuestionAnswerPair(models.Model):
    question_text = models.TextField()
    answer_text = models.TextField()
    def __str__(self) -> str:
        return self.question_text + " " + self.answer_text
    

class ModelX(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name or ''

koodipaja/testaus/forms.py
from django.forms import ModelForm
from .models import Malli1, Malli2, Muistipeli, ModelX


class MuistipeliForm(ModelForm):
    class Meta:
        model = Muistipeli
        fields = ['title']


class Malli1Form(ModelForm):
    class Meta:
        model = Malli1
        fields = ['owner', 'muistipeli', 'question', 'answer']


class Malli2Form(ModelForm):
    class Meta:
        model = Malli2
        fields = ['owner', 'muistipeli', 'question', 'answer']


class ModelXForm(ModelForm):
    class Meta:
        model = ModelX
        fields = ['name']

koodipaja/testaus/views.py
from json import dumps
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from users.models import Profile
from projects.models import ProjectArticle
from .models import MyModel, Malli1, Malli2, QuestionAnswerPair, ModelX
from .forms import Malli1Form, Malli2Form, MuistipeliForm, ModelXForm
from rest_framework import viewsets
from pprint import pprint


def cards_test_page(request):
    # Render the template with the JavaScript file
    return render(request, 'testing/cards_test.html')

def get_data(request):
    # Retrieve data from the database
    question_answer_pairs = QuestionAnswerPair.objects.all()

    # Serialize the data to JSON
    serialized_data = [{'question': pair.question_text, 'answer': pair.answer_text} for pair in question_answer_pairs]
    print(serialized_data)

    # Return JSON response
    return JsonResponse(serialized_data, safe=False)

def test_modelx(request):
    stuff = ModelX.objects.all()

    context = {'stuff': stuff}

    return render(request, 'testing/empty_test_page copy.html', context)

# ModelX form
# TODO: Try to make each box clickable that spawns a correct modal/dialog that supports multiple desired operations. If/when that's done, maybe could try something funky with overflow-x at some point (check ideas.txt)
# check empty_test_page.html, empty_test_page copy.html, # empty_test_page copy 2.html, # empty_test_page copy 3.html
def add_model_x(request):
    if request.method == 'POST':
        form = ModelXForm(request.POST)
        if form.is_valid():
            form = form.save()

            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    
    else:
        form = ModelXForm()

    return render(request, 'testing/modelx_form.html', {'form': form})



from .serializers import QuestionAnswerPairSerializer

# API
class QuestionAnswerPairViewSet(viewsets.ModelViewSet):
    queryset = QuestionAnswerPair.objects.all()
    serializer_class = QuestionAnswerPairSerializer

















################################################################

def testingHomepage(request):
    return render(request, 'main_testing.html')


def general_testing(request):
    questions = Malli2.objects.values('question')
    anwers = Malli2.objects.values('answer')

    lista = []
    sk = {}
    for x,y in zip(questions, anwers):
        sk['question'] = x['question']
        sk['answer'] = y['answer']
        lista.append(sk)
    # pprint(lista)
    
    context = {'questions':questions, 'answers':anwers}

    return render(request, 'testing/general_testing_page.html', context)


def empty_test_page(request):
    articles = ProjectArticle.objects.filter(favorite=True)

    context = {'articles': articles}

    return render(request, 'testing/empty_test_page.html', context)


def toggle_boolean(request, pk):
    my_object = get_object_or_404(MyModel, pk=pk)
    
    if request.method == "POST":
        # Toggle the BooleanField value
        my_object.my_boolean_field = not my_object.my_boolean_field
        my_object.save()

        return redirect('testaus:toggle-boolean', pk)

    # Render the template for normal page rendering
    return render(request, 'testing/my_template.html', {'my_object': my_object})


# Muistipeli

@login_required(login_url='users:login')
def muistipeli(request):
    if request.user.is_authenticated:
        profile = request.user.profile
        malli1 = profile.malli1_set.all()

        malli2 = profile.malli2_set.all()
    else:
        return redirect('users:login')

    context = {'malli1': malli1, 'malli2': malli2}
    return render(request, 'testing/muistipeli.html', context)


@login_required(login_url='users:login')
def new_muistipeli(request):

    form = MuistipeliForm()

    if request.method == 'POST':
        form = MuistipeliForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('testaus:muistipeli')

    context = {'form': form}

    return render(request, 'testing/muistipeli_form.html', context)


@login_required(login_url='users:login')
def create_malli1(request):

    form = Malli1Form()

    if request.method == 'POST':
        form = Malli1Form(request.POST)
        if form.is_valid():
            form.save()

            return redirect('testaus:muistipeli')

    context = {'form': form}

    return render(request, 'testing/malli1_form.html', context)


def move_question_to_active(request, pk):
    model1_instance = Malli1.objects.get(id=pk)
    initial_values = {
        'owner': model1_instance.owner,
        'muistipeli': model1_instance.muistipeli,
        'question': model1_instance.question,
        'answer': model1_instance.answer
    }

    if request.method == 'POST':
        form = Malli1Form(request.POST)
        if form.is_valid():
            # Create a new instance of Model2 and copy the data from Model1
            model2_instance = Malli2(
                owner=form.cleaned_data['owner'],
                muistipeli=form.cleaned_data['muistipeli'],
                question=form.cleaned_data['question'],
                answer=form.cleaned_data['answer'],
                # Copy more fields from Model1 as needed
            )
            model2_instance.save()

            # Delete the original Model1 instance
            model1_instance.delete()

            # Redirect to a success view after successful submission
            return redirect('testaus:muistipeli')
    else:
        form = Malli1Form(initial=initial_values)

    context = {'form': form}

    return render(request, 'testing/active_question_form.html', context)


def move_question_to_inactive(request, pk):
    model2_instance = Malli2.objects.get(id=pk)
    initial_values = {
        'owner': model2_instance.owner,
        'muistipeli': model2_instance.muistipeli,
        'question': model2_instance.question,
        'answer': model2_instance.answer
    }

    if request.method == 'POST':
        form = Malli2Form(request.POST)
        if form.is_valid():
            # Create a new instance of Model2 and copy the data from Model1
            model1_instance = Malli1(
                owner=form.cleaned_data['owner'],
                muistipeli=form.cleaned_data['muistipeli'],
                question=form.cleaned_data['question'],
                answer=form.cleaned_data['answer'],
                # Copy more fields from Model1 as needed
            )
            model1_instance.save()

            # Delete the original Model1 instance
            model2_instance.delete()

            # Redirect to a success view after successful submission
            return redirect('testaus:muistipeli')
    else:
        form = Malli2Form(initial=initial_values)

    context = {'form': form}

    return render(request, 'testing/inactive_question_form.html', context)

# geeksforgeeks example


def send_dictionary(request):
    mallit = Malli2.objects.all()
    q_a_pairs = QuestionAnswerPair.objects.all()

    mallit_dict = []
    q_a_pair_dict = []

    for obj in mallit:
        obj_dict = {}
        obj_dict = {
            'question': obj.question,
            'answer': obj.answer
        }

        # Append the dictionary to the list
        mallit_dict.append(obj_dict)

    for obj in q_a_pairs:
        obj_dict = {}
        obj_dict = {
            'question': obj.question_text,
            'answer': obj.answer_text
        }

        # Append the dictionary to the list
        q_a_pair_dict.append(obj_dict)


    try:
        dataJSON = dumps(q_a_pair_dict)
        return render(request, 'testing/landing.html', {'data': dataJSON})
    except:
        return render(request, 'testing/landing.html')

koodipaja/testaus/templates/testing/active_question_form.html
{% extends 'main.html' %}
{% block content %}

<main>
    <div>
        <div>
            <button onclick="history.back()">Go Back</button>
            <hr>

            <form class="form" id="moveGame" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <table>
                    <tr>
                        <th>
                        <td>
                            <label for="formInput#text">{{field.label}}</label>
                        </td>
                        </th>
                    </tr>
                    <tr>
                        <th>
                        <td name="task" id="task">
                            {{field}}
                        </td>
                        </th>
                    </tr>
                </table>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

<script>
    window.addEventListener('DOMContentLoaded', function () {
        var shouldAutoSubmit = true;  // Set the value based on your logic

        if (shouldAutoSubmit) {
            // Wait for a short delay, then submit the form
            setTimeout(function () {
                document.getElementById('moveGame').submit();
            }, 0);  // Adjust the delay as needed
        }
    });
</script>


{% endblock content %}

koodipaja/testaus/templates/testing/empty_test_page copy 2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD Modal Example</title>
    <!-- Include Bootstrap CSS (for modal styling) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- Include Bootstrap JS (required for modal functionality) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <style>
        .square {
            width: 100px;
            height: 100px;
            background-color: #3498db;
            margin: 10px;
        }
    </style>
</head>

<body>
    <!-- WITH BOOTSTRAP -->

    <!-- Modal -->
    <div class="modal" id="add-x-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Add Model X</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal Body -->
                <div class="modal-body">
                    <form id="add-x-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <!-- Add more form fields as needed -->
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Button to open modal -->
    <button type="button" class="btn btn-primary" id="open-modal-button" data-toggle="modal" data-target="#add-x-modal">
        Open Add Model X Modal
    </button>
    <hr>
    {% for stuff in stuff %}
    <div class="square">{{ stuff.name }}</div>
    {% endfor %}

    <!-- JavaScript code -->
    <script>
        $(document).ready(function () {
            // Function to open modal
            function openModal(modalId) {
                $(`#${modalId}`).modal('show');
            }

            // Function to close modal
            function closeModal(modalId) {
                $(`#${modalId}`).modal('hide');
            }

            // Handle form submission using AJAX when modal form is submitted
            $('#add-x-form').submit(function (e) {
                e.preventDefault();
                const formData = $(this).serialize();
                $.post('/add_model_x/', formData)
                    .done(function (response) {
                        // Handle success, for example:
                        // Close the modal
                        closeModal('add-x-modal');
                        // Reload the page to see changes
                        location.reload();
                    })
                    .fail(function (xhr, status, error) {
                        // Handle errors, for example:
                        console.error('Error:', error);
                        alert('An error occurred while submitting the form.');
                    });
            });

            // Close the modal when the close button is clicked
            $('.modal .close').click(function () {
                closeModal('add-x-modal');
            });
        });
    </script>

</body>

</html>

koodipaja/testaus/templates/testing/empty_test_page copy 3.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD Modal Example</title>
    <style>
        .square {
            width: 100px;
            height: 100px;
            background-color: #3498db;
            margin: 10px;
        }

        /* Modal styles */
        .modal {
            display: none;
            /* Hide modal by default */
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.4);
        }

        .modal-content {
            background-color: white;
            margin: 20% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 50%;
            max-width: 400px;
        }

        .close {
            position: absolute;
            top: 10px;
            right: 10px;
            font-size: 20px;
            cursor: pointer;
        }

        /* Add more styles as needed */
    </style>
</head>

<body>
    <!-- WITHOUT BOOTSTRAP WORKING -->

    <!-- Modal -->
    <div id="add-x-modal" class="modal">
        <div class="modal-content">
            <span class="close" id="close-modal">&times;</span>
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add Model X</h4>
            </div>
            <!-- Modal Body -->
            <div class="modal-body">
                <form id="add-x-form">
                    <!-- Include CSRF token if using Django -->
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" id="name" name="name" required>
                    </div>
                    <!-- Add more form fields as needed -->
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Button to open modal -->
    <button type="button" id="open-modal-button">Open Add Model X Modal</button>
    <hr>
    {% for stuff in stuff %}
    <div class="square">{{ stuff.name }}</div>
    {% endfor %}

    <script>
        // Function to open modal
        function openModal(modalId) {
            document.getElementById(modalId).style.display = "block";
        }

        // Function to close modal
        function closeModal(modalId) {
            document.getElementById(modalId).style.display = "none";
        }

        // Handle form submission using AJAX when modal form is submitted
        document.getElementById('add-x-form').addEventListener('submit', function (e) {
            e.preventDefault();
            const formData = new FormData(this);
            fetch('/add_model_x/', {
                method: 'POST',
                body: formData
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    // Handle success, for example:
                    // Close the modal
                    closeModal('add-x-modal');
                    // Reload the page to see changes
                    location.reload();
                })
                .catch(error => {
                    // Handle errors, for example:
                    console.error('Error:', error);
                    alert('An error occurred while submitting the form.');
                });
        });

        // Open the modal when the "Open Add Model X Modal" button is clicked
        document.getElementById('open-modal-button').addEventListener('click', function () {
            openModal('add-x-modal');
        });

        // Close the modal when the close button is clicked
        document.getElementById('close-modal').addEventListener('click', function () {
            closeModal('add-x-modal');
        });

    </script>
</body>

</html>

koodipaja/testaus/templates/testing/empty_test_page copy.html
<!-- my_template.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Model X Squares</title>
    <style>
        .square {
            width: 100px;
            height: 100px;
            background-color: #3498db;
            margin: 10px;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body>
    {% for stuff in stuff %}
    <div class="square">{{ stuff.name }}</div>
    {% endfor %}

    <!-- Button to open the modal -->
    <button id="add-x-button">Add Model X</button>

    <!-- Modal -->
    <div class="modal" id="add-x-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="add-x-form">
                    {% csrf_token %}
                    <!-- Fields for Model X data -->
                    <input type="text" name="name" placeholder="Name">
                    <button type="submit">Add</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            // Function to open modal
            function openModal(modalId) {
                document.getElementById(modalId).style.display = "block";
            }

            // Function to close modal
            function closeModal(modalId) {
                document.getElementById(modalId).style.display = "none";
            }

            // Handle form submission using AJAX when modal form is submitted
            $('#add-x-form').submit(function (e) {
                e.preventDefault();
                const formData = $(this).serialize();
                $.post('/add_model_x/', formData)
                    .done(function (response) {
                        // Handle success, for example:
                        // Close the modal
                        closeModal('add-x-modal');
                        // Reload the page to see changes
                        location.reload();
                    })
                    .fail(function (xhr, status, error) {
                        // Handle errors, for example:
                        console.error('Error:', error);
                        alert('An error occurred while submitting the form.');
                    });
            });

            // Open the modal when the "Create New Item" button is clicked
            $('#open-modal-button').click(function () {
                openModal('add-x-modal');
            });

            // Close the modal when the close button is clicked
            $('.modal .close').click(function () {
                closeModal('add-x-modal');
            });
        });

        // $(document).ready(function () {
        //     // Handle form submission using AJAX
        //     $('#add-x-form').submit(function (e) {
        //         e.preventDefault();
        //         const formData = $(this).serialize();
        //         $.post('/add_model_x/', formData)
        //             .done(function (response) {
        //                 // Handle success, for example:
        //                 location.reload();
        //             })
        //             .fail(function (xhr, status, error) {
        //                 // Handle errors, for example:
        //                 console.error('Error:', error);
        //                 alert(error);
        //             });
        //     });
        // });

    </script>

</body>

</html>

koodipaja/testaus/templates/testing/modelx_form.html
<form id="add-x-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Model X</button>
</form>

koodipaja/testaus/templates/testing/muistipeli.html
{% extends "main.html" %} {% load static %} {% block content %}

<button onclick="history.back()">Go Back</button>
<div>
  <a style="font-size: x-large" href="{% url 'testaus:new-muistipeli' %}"
    >Create new memory card&nbsp;</a
  >
</div>
<hr />
<div>
  <a style="font-size: x-large" href="{% url 'testaus:create-malli-1' %}"
    >Create new question and answer&nbsp;</a
  >
</div>

<hr />

<style>
  .table {
    width: 30%;
  }
</style>

<div class="tables-container">
  <div class="table">
    <table class="left-table">
      <thead>
        <tr>
          <th>Inactive</th>
        </tr>
      </thead>
      <tbody>
        {% for malli1 in malli1 %}
        <tr>
          <td>{{ malli1.question }}</td>
          <td class="arrow-cell right-arrow">
            <a
              style="font-size: 20px; margin-left: 5px"
              href="{% url 'testaus:move-question-to-active' malli1.id %}"
              >&gt;&gt;</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="table">
    <table class="middle-table">
      <thead>
        <tr>
          <th>Active</th>
        </tr>
      </thead>
      <tbody>
        {% for malli2 in malli2 %}
        <tr>
          <td class="arrow-cell left-arrow">
            <a
              style="font-size: 20px; margin-right: 5px"
              href="{% url 'testaus:move-question-to-inactive' malli2.id %}"
              >&lt;&lt;</a
            >
          </td>
          <td>{{ malli2.question }}</td>
          <td class="arrow-cell right-arrow">
            <a style="font-size: 20px; margin-left: 5px" href="">&gt;&gt;</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="table">
    <table class="right-table">
      <thead>
        <tr>
          <th>Learned</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="arrow-cell left-arrow">&lt;</td>
          <td>hard coded test stuff</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

koodipaja/testaus/templates/testing/my_template.html
{% extends "main.html" %} {% block content %}
<form method="POST">
  {% csrf_token %}
  <h1 id="booleanField">{{ my_object.my_boolean_field }}</h1>

  <button id="toggle-button" data-object-id="{{ my_object.pk }}">Toggle</button>
</form>
{% endblock %}